PATCH  http://localhost:3000/Projects/Quotation/Customers
content-type: application/json

{
    "inDataToInsert":{
    "uuidv4":"c6764683-b5b9-46e4-b4aa-644b792a8478",
        "CustomerName":"Raja---",
        "CustomerContact:":111
    }
}